# Aula 06 - Aplicação Numpy e Scipy em sistemas lineares

É muito importante que se domine operações lineares e sua modelagem computacional com `python`

Essas ferramentas nos dão a possibilidade maior de aplicar a noção de arrays para problemas reais. É muito mais versátil tratar diversos problemas na programação com vetores -> matrizes -> arrays


## 3.1 Por que o numpy é tão utilizado e mais eficiente ? 

### NumPy Arrays vs Python Lists:

1. **Homogeneous vs Heterogeneous Data Types**: `NumPy arrays` armazenam dados de um único tipo de forma contígua, enquanto listas em Python podem conter tipos de dados mistos, resultando em uma alocação de memória menos eficiente.



2. **Paralelismo**: Pacote divide uma tarefa em vários fragmentos e então processa todos os fragmentos em paralelo



3. **Integração de C, C++ e Fortran**: NumPy é baseado em código C e usa funções C otimizadas para muitas operações internas. Além disso, muitas bibliotecas NumPy são implementadas em C++, Fortran, contribuindo para sua eficiência.




In [1]:
# importing required packages
import numpy
import time


# size of arrays and lists
size = 1000000

# declaring lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# Concatenation
print("\nConcatenation:")

# list
initialTime = time.time()
list1 = list1 + list2

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = numpy.concatenate((array1, array2),
						axis = 0)

# calculating execution time 
print("Time taken by NumPy Arrays :", 
	(time.time() - initialTime),
	"seconds")


# Dot Product
dot = 0
print("\nDot Product:")

# list
initialTime = time.time()
for a, b in zip(list1, list2):
		dot = dot + (a * b)
		
# calculating execution time
print("Time taken by Lists :", 
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = numpy.dot(array1, array2)

# calculating execution time 
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


# Scalar Addition 
print("\nScalar Addition:")

# list
initialTime = time.time()
list1 =[i + 2 for i in range(size)]

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array1 = array1 + 2

# calculating execution time 
print("Time taken by NumPy Arrays :", 
	(time.time() - initialTime), 
	"seconds")


# Deletion
print("\nDeletion: ")

# list
initialTime = time.time()
del(list1)

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
del(array1)

# calculating execution time 
print("Time taken by NumPy Arrays :", 
	(time.time() - initialTime),
	"seconds")



Concatenation:
Time taken by Lists : 0.05274844169616699 seconds
Time taken by NumPy Arrays : 0.01527547836303711 seconds

Dot Product:
Time taken by Lists : 0.30832648277282715 seconds
Time taken by NumPy Arrays : 0.005681037902832031 seconds

Scalar Addition:
Time taken by Lists : 0.13402414321899414 seconds
Time taken by NumPy Arrays : 0.010125875473022461 seconds

Deletion: 
Time taken by Lists : 0.02484297752380371 seconds
Time taken by NumPy Arrays : 7.009506225585938e-05 seconds


## 3.2 Sistemas de equações lineares

#### Equações lineares 

$ a_{1}x_1 + a_{2}x_2 + \ldots + a_{n}x_n = b $

- Definição: Um sistema linear é um conjunto de equações lineares


$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \ldots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \ldots + a_{2n}x_n = b_2 \\
\vdots \\
a_{m1}x_1 + a_{m2}x_2 + \ldots + a_{mn}x_n = b_m \\
\end{cases}
$$


Sistemas lineares podem ser resolvidos por escalonamento pelo método de Gauss Jordan, mas esse algoritmo é um tanto quanto trabalhoso e sua implementação computacional não parece ser a mais simples. Ao invés disso veja como podemos usar a propriedade da inversibilidade de matrizes para resolver esse problema:

### Problema: Resolver o seguinte sistema linear
$$
2x_1 + 3x_2  + 4x_3 = 46 \\
1x_1 + 1x_2 +  3x_3 = 28 \\
3x_1 + 5x_2 +  1x_3 = 36 \\
$$

Podemos colocar o sistema sob a forma de matrizes : Aqui 3 matrizes são necessárias

- Matriz dos coeficientes:


\begin{equation}
\begin{pmatrix}
  2       & 3   & 4 \\
  1       & 1   & 3 \\
  3       & 5   &  1 \\
\end{pmatrix}
= A
\end{equation}

- Matriz coluna das incognitas:

\begin{equation}
\begin{pmatrix}
  x_{1}\\
  x_{2} \\
  x_{3}\\

\end{pmatrix}
= X
\end{equation}

- Matriz das variáveis independentes

\begin{equation}
\begin{pmatrix}
  46\\
  28 \\
  36\\

\end{pmatrix}
= Y
\end{equation}

De modo que

\begin{equation}
\begin{pmatrix}
  2       & 3   & 4 \\
  1       & 1   & 3 \\
  3       & 5   &  1 \\
\end{pmatrix}
\begin{pmatrix}
  x_{1}\\
  x_{2} \\
  x_{3}\\

\end{pmatrix}
=
\begin{pmatrix}
  46\\
  28 \\
  36\\

\end{pmatrix}

\end{equation}

Dado que a matriz $A$ admita uma matriz inversa $A^{-1}$
$$
A X  = Y \\

A^{-1} A X = A^{-1} Y \\

(A^{-1} A) X = A^{-1} Y \\

I X = A^{-1} Y \\

X = A^{-1} Y 

$$










#### Implementando ...
Vamos criar as matrizes que já temos

In [2]:
## vamos fazer a implementação desse problema

import numpy as np 


matriz_coef = np.array([ [2,3,4],
                       [1,1,3],
                       [3,5,1] ])
print(matriz_coef)
print(f'Matriz {matriz_coef.shape[0]} x {matriz_coef.shape[1]}')

[[2 3 4]
 [1 1 3]
 [3 5 1]]
Matriz 3 x 3


In [3]:
matriz_Y  = np.array( [[46],
                       [28],
                       [36] ])

print(matriz_Y)
print(f'Matriz coluna {matriz_Y.shape[0]} x {matriz_Y.shape[1]}')

[[46]
 [28]
 [36]]
Matriz coluna 3 x 1


### Encontrando a matriz inversa e multiplicação de arrays

In [4]:
## multiplicação entre arrays - > metodo .dot() ou @
## antes encontremos a inversa

## biblioteca scipy modulo linalg

from scipy import linalg

matriz_inv  = linalg.inv(matriz_coef)
matriz_inv



array([[-3.5 ,  4.25,  1.25],
       [ 2.  , -2.5 , -0.5 ],
       [ 0.5 , -0.25, -0.25]])

In [5]:
##usando dot
X_dot = np.dot(matriz_inv, matriz_Y)

X  = matriz_inv @ matriz_Y

print(f' Matriz com .dot: \n {X_dot} \n \n')

print(f'Matriz com @ \n {X}')


 Matriz com .dot: 
 [[3.]
 [4.]
 [7.]] 
 

Matriz com @ 
 [[3.]
 [4.]
 [7.]]


In [6]:
solucao = f''' A solução então é tal que \n
               x1 = {round(X[0, 0])} 
               x2 = {round(X[1, 0])} 
               x3 = {round(X[2, 0])} 
'''

print(solucao)

 A solução então é tal que 

               x1 = 3 
               x2 = 4 
               x3 = 7 

